export type { ITransaction } from './dataAccess/ITransaction'
export type { ITransactionManager } from './dataAccess/ITransactionManager'
export type { IDataConnectionProvider } from './dataAccess/IDataConnectionProvider'
export type { ITransactionAware } from './dataAccess/ITransactionAware'
export type { IDataAccessProvider } from './dataAccess/IDataAccessProvider'
export type { IQueryBuilder } from './dataAccess/IQueryBuilder'
export type { IRawQueryBuilder } from './dataAccess/IRawQueryBuilder'
export type { IRepositoryHelpers } from './repositories/IRepositoryHelpers'
export { RepositoryBase } from './repositories/RepositoryBase'

export { ConcurrencyError } from './errors/ConcurrencyError'
export { DataPersistenceError } from './errors/DataPersistenceError'
export { InvalidRequestError } from './errors/InvalidRequestError'
export { ConnectionError } from './errors/ConnectionError'
