# fly.toml app configuration file generated for hatsuportal on 2026-07-15T23:56:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hatsuportal'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "sh -c 'npm run db:migrate --workspace=backend'"

[env]
  NODE_ENV = 'prod'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/api/v1/ping'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
