import { IHttpErrorMapper } from '@hatsuportal/platform'
import { NextFunction, Request, Response } from 'express'
import { ValidateError } from 'tsoa'
import { Logger } from '@hatsuportal/platform'

const logger = new Logger('ErrorMiddleware')

/**
 * Failsafe middleware if for any reason an exception it mistakenly thrown from a Controller endpoint
 */
export function createErrorMiddleware(httpErrorMapper: IHttpErrorMapper) {
  return (error: Error, request: Request, response: Response, next: NextFunction) => {
    /**
     * TSOA automatically validates json input based on the swagger.json generated by controllers.
     * The ValidateError is thrown if a users request is invalid in comparison to the swagger/open api specs
     */
    if (error instanceof ValidateError) {
      logger.warn(`Caught TSOA API Validation Error for ${request.path}:`, error.fields)
      logger.warn(error)
      return response.status(422).json({
        message: 'Validation Failed',
        details: error?.fields
      })
    }

    const httpError = httpErrorMapper.mapApplicationErrorToHttpError(error)
    const statusFromError = (error as Error & { status?: number }).status

    return response
      .status(
        httpError.status === 500 && typeof statusFromError === 'number' && statusFromError >= 400 && statusFromError < 600
          ? statusFromError
          : httpError.status
      )
      .json(httpError)
  }
}
