export { UserId } from './valueObjects/UserId'
export { SystemUserId } from './valueObjects/SystemUserId'
export { UserName } from './valueObjects/UserName'
export { Email } from './valueObjects/Email'
export { Password } from './valueObjects/Password'
export { UserRole } from './valueObjects/UserRole'
export { ThemeId } from './valueObjects/ThemeId'
export { DefaultThemeId } from './valueObjects/DefaultThemeId'
export { ThemeName } from './valueObjects/ThemeName'
export { ThemeColors } from './valueObjects/ThemeColors'
export { ColorScheme, ColorSchemeEnum } from './valueObjects/ColorScheme'
export { ProfileImageId } from './valueObjects/ProfileImageId'
export { StatusMessage } from './valueObjects/StatusMessage'
export { Bio } from './valueObjects/Bio'
export { NotificationSettings, type NotificationSettingsProps } from './valueObjects/NotificationSettings'

export { User, UserProps } from './entities/User'
export { Theme, ThemeProps } from './entities/Theme'
export type { IUserCredentials } from './models/IUserCredentials'

export { InvalidEmailError } from './errors/InvalidEmailError'
export { InvalidUserIdError } from './errors/InvalidUserIdError'
export { InvalidPasswordError } from './errors/InvalidPasswordError'
export { InvalidRoleListError } from './errors/InvalidRoleListError'
export { UserNameEmptyError } from './errors/UserNameEmptyError'
export { UserNameTooLongError } from './errors/UserNameTooLongError'
export { BioTooLongError } from './errors/BioTooLongError'
export { InvalidBioError } from './errors/InvalidBioError'
export { StatusMessageTooLongError } from './errors/StatusMessageTooLongError'
export { InvalidStatusMessageError } from './errors/InvalidStatusMessageError'
export { InvalidUserRoleError } from './errors/InvalidUserRoleError'
export { InvalidProfileImageIdError } from './errors/InvalidProfileImageIdError'
export { InvalidThemeIdError } from './errors/InvalidThemeIdError'
export { InvalidThemeNameError } from './errors/InvalidThemeNameError'
export { CannotDeleteDefaultThemeError } from './errors/CannotDeleteDefaultThemeError'
export { InactiveUserCannotChangePreferencesError } from './errors/InactiveUserCannotChangePreferencesError'

export type { IUserWriteRepository } from './repositories/IUserWriteRepository'
export type { IThemeRepository } from './repositories/IThemeRepository'

export type { IPasswordPolicy } from './policies/IPasswordPolicy'
export type { IPasswordFactory } from './authentication/IPasswordFactory'

export { UserCreatedEvent, UserUpdatedEvent, UserDeactivatedEvent, UserDeletedEvent } from './events/UserEvents'
